'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace axBOMService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CallContext", [Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CallContext
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LanguageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogonAsUserField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PartitionKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PropertyBagField As System.Collections.Generic.Dictionary(Of String, String)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Language() As String
            Get
                Return Me.LanguageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LanguageField, value) <> true) Then
                    Me.LanguageField = value
                    Me.RaisePropertyChanged("Language")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LogonAsUser() As String
            Get
                Return Me.LogonAsUserField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LogonAsUserField, value) <> true) Then
                    Me.LogonAsUserField = value
                    Me.RaisePropertyChanged("LogonAsUser")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MessageId() As String
            Get
                Return Me.MessageIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageIdField, value) <> true) Then
                    Me.MessageIdField = value
                    Me.RaisePropertyChanged("MessageId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PartitionKey() As String
            Get
                Return Me.PartitionKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PartitionKeyField, value) <> true) Then
                    Me.PartitionKeyField = value
                    Me.RaisePropertyChanged("PartitionKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PropertyBag() As System.Collections.Generic.Dictionary(Of String, String)
            Get
                Return Me.PropertyBagField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PropertyBagField, value) <> true) Then
                    Me.PropertyBagField = value
                    Me.RaisePropertyChanged("PropertyBag")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="XppObjectBase", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(axBOMService.V2AX_BOMLineDataContract)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(axBOMService.V2AX_ItemListDataContract)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(axBOMService.V2AX_BOMHeaderDataContract))>  _
    Partial Public Class XppObjectBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="V2AX_BOMLineDataContract", [Namespace]:="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application"),  _
     System.SerializableAttribute()>  _
    Partial Public Class V2AX_BOMLineDataContract
        Inherits axBOMService.XppObjectBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BOMNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BomQtyField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LengthField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LineNoField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PCSField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PositionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RevNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WidthField As Decimal
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BOMNo() As String
            Get
                Return Me.BOMNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BOMNoField, value) <> true) Then
                    Me.BOMNoField = value
                    Me.RaisePropertyChanged("BOMNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BomQty() As Decimal
            Get
                Return Me.BomQtyField
            End Get
            Set
                If (Me.BomQtyField.Equals(value) <> true) Then
                    Me.BomQtyField = value
                    Me.RaisePropertyChanged("BomQty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ItemNo() As String
            Get
                Return Me.ItemNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemNoField, value) <> true) Then
                    Me.ItemNoField = value
                    Me.RaisePropertyChanged("ItemNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Length() As Decimal
            Get
                Return Me.LengthField
            End Get
            Set
                If (Me.LengthField.Equals(value) <> true) Then
                    Me.LengthField = value
                    Me.RaisePropertyChanged("Length")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LineNo() As Decimal
            Get
                Return Me.LineNoField
            End Get
            Set
                If (Me.LineNoField.Equals(value) <> true) Then
                    Me.LineNoField = value
                    Me.RaisePropertyChanged("LineNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PCS() As Decimal
            Get
                Return Me.PCSField
            End Get
            Set
                If (Me.PCSField.Equals(value) <> true) Then
                    Me.PCSField = value
                    Me.RaisePropertyChanged("PCS")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Position() As String
            Get
                Return Me.PositionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PositionField, value) <> true) Then
                    Me.PositionField = value
                    Me.RaisePropertyChanged("Position")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RevNo() As String
            Get
                Return Me.RevNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RevNoField, value) <> true) Then
                    Me.RevNoField = value
                    Me.RaisePropertyChanged("RevNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Width() As Decimal
            Get
                Return Me.WidthField
            End Get
            Set
                If (Me.WidthField.Equals(value) <> true) Then
                    Me.WidthField = value
                    Me.RaisePropertyChanged("Width")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="V2AX_ItemListDataContract", [Namespace]:="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application"),  _
     System.SerializableAttribute()>  _
    Partial Public Class V2AX_ItemListDataContract
        Inherits axBOMService.XppObjectBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChargesCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IntegrationDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemGroupField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PcsControlledField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RemarksField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SearchNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SpecificationField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ChargesCode() As String
            Get
                Return Me.ChargesCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChargesCodeField, value) <> true) Then
                    Me.ChargesCodeField = value
                    Me.RaisePropertyChanged("ChargesCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CompName() As String
            Get
                Return Me.CompNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompNameField, value) <> true) Then
                    Me.CompNameField = value
                    Me.RaisePropertyChanged("CompName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IntegrationDate() As Date
            Get
                Return Me.IntegrationDateField
            End Get
            Set
                If (Me.IntegrationDateField.Equals(value) <> true) Then
                    Me.IntegrationDateField = value
                    Me.RaisePropertyChanged("IntegrationDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ItemGroup() As String
            Get
                Return Me.ItemGroupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemGroupField, value) <> true) Then
                    Me.ItemGroupField = value
                    Me.RaisePropertyChanged("ItemGroup")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PcsControlled() As Boolean
            Get
                Return Me.PcsControlledField
            End Get
            Set
                If (Me.PcsControlledField.Equals(value) <> true) Then
                    Me.PcsControlledField = value
                    Me.RaisePropertyChanged("PcsControlled")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductName() As String
            Get
                Return Me.ProductNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameField, value) <> true) Then
                    Me.ProductNameField = value
                    Me.RaisePropertyChanged("ProductName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductNo() As String
            Get
                Return Me.ProductNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNoField, value) <> true) Then
                    Me.ProductNoField = value
                    Me.RaisePropertyChanged("ProductNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Remarks() As String
            Get
                Return Me.RemarksField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RemarksField, value) <> true) Then
                    Me.RemarksField = value
                    Me.RaisePropertyChanged("Remarks")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SearchName() As String
            Get
                Return Me.SearchNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SearchNameField, value) <> true) Then
                    Me.SearchNameField = value
                    Me.RaisePropertyChanged("SearchName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Specification() As String
            Get
                Return Me.SpecificationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SpecificationField, value) <> true) Then
                    Me.SpecificationField = value
                    Me.RaisePropertyChanged("Specification")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="V2AX_BOMHeaderDataContract", [Namespace]:="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application"),  _
     System.SerializableAttribute()>  _
    Partial Public Class V2AX_BOMHeaderDataContract
        Inherits axBOMService.XppObjectBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApprovedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BOMDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BOMNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BOMNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BomLineField() As axBOMService.V2AX_BOMLineDataContract
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BomQtyField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CheckedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RevDescChangesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RevNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SNField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ApprovedBy() As String
            Get
                Return Me.ApprovedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApprovedByField, value) <> true) Then
                    Me.ApprovedByField = value
                    Me.RaisePropertyChanged("ApprovedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BOMDate() As Date
            Get
                Return Me.BOMDateField
            End Get
            Set
                If (Me.BOMDateField.Equals(value) <> true) Then
                    Me.BOMDateField = value
                    Me.RaisePropertyChanged("BOMDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BOMName() As String
            Get
                Return Me.BOMNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BOMNameField, value) <> true) Then
                    Me.BOMNameField = value
                    Me.RaisePropertyChanged("BOMName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BOMNo() As String
            Get
                Return Me.BOMNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BOMNoField, value) <> true) Then
                    Me.BOMNoField = value
                    Me.RaisePropertyChanged("BOMNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BomLine() As axBOMService.V2AX_BOMLineDataContract()
            Get
                Return Me.BomLineField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BomLineField, value) <> true) Then
                    Me.BomLineField = value
                    Me.RaisePropertyChanged("BomLine")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BomQty() As Decimal
            Get
                Return Me.BomQtyField
            End Get
            Set
                If (Me.BomQtyField.Equals(value) <> true) Then
                    Me.BomQtyField = value
                    Me.RaisePropertyChanged("BomQty")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CheckedBy() As String
            Get
                Return Me.CheckedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CheckedByField, value) <> true) Then
                    Me.CheckedByField = value
                    Me.RaisePropertyChanged("CheckedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ItemNo() As String
            Get
                Return Me.ItemNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemNoField, value) <> true) Then
                    Me.ItemNoField = value
                    Me.RaisePropertyChanged("ItemNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RevDescChanges() As String
            Get
                Return Me.RevDescChangesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RevDescChangesField, value) <> true) Then
                    Me.RevDescChangesField = value
                    Me.RaisePropertyChanged("RevDescChanges")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RevNo() As String
            Get
                Return Me.RevNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RevNoField, value) <> true) Then
                    Me.RevNoField = value
                    Me.RaisePropertyChanged("RevNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SN() As String
            Get
                Return Me.SNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SNField, value) <> true) Then
                    Me.SNField = value
                    Me.RaisePropertyChanged("SN")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AifFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomDetailXmlField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaultMessageListArrayField() As axBOMService.FaultMessageList
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InfologMessageListField() As axBOMService.InfologMessage
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StackTraceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XppExceptionTypeField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomDetailXml() As String
            Get
                Return Me.CustomDetailXmlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomDetailXmlField, value) <> true) Then
                    Me.CustomDetailXmlField = value
                    Me.RaisePropertyChanged("CustomDetailXml")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaultMessageListArray() As axBOMService.FaultMessageList()
            Get
                Return Me.FaultMessageListArrayField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaultMessageListArrayField, value) <> true) Then
                    Me.FaultMessageListArrayField = value
                    Me.RaisePropertyChanged("FaultMessageListArray")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InfologMessageList() As axBOMService.InfologMessage()
            Get
                Return Me.InfologMessageListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InfologMessageListField, value) <> true) Then
                    Me.InfologMessageListField = value
                    Me.RaisePropertyChanged("InfologMessageList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StackTrace() As String
            Get
                Return Me.StackTraceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StackTraceField, value) <> true) Then
                    Me.StackTraceField = value
                    Me.RaisePropertyChanged("StackTrace")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XppExceptionType() As Integer
            Get
                Return Me.XppExceptionTypeField
            End Get
            Set
                If (Me.XppExceptionTypeField.Equals(value) <> true) Then
                    Me.XppExceptionTypeField = value
                    Me.RaisePropertyChanged("XppExceptionType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FaultMessageList", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FaultMessageList
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentOperationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaultMessageArrayField() As axBOMService.FaultMessage
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FieldField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceOperationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceOperationParameterField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XPathField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XmlLineField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XmlPositionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Document() As String
            Get
                Return Me.DocumentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentField, value) <> true) Then
                    Me.DocumentField = value
                    Me.RaisePropertyChanged("Document")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DocumentOperation() As String
            Get
                Return Me.DocumentOperationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentOperationField, value) <> true) Then
                    Me.DocumentOperationField = value
                    Me.RaisePropertyChanged("DocumentOperation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaultMessageArray() As axBOMService.FaultMessage()
            Get
                Return Me.FaultMessageArrayField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaultMessageArrayField, value) <> true) Then
                    Me.FaultMessageArrayField = value
                    Me.RaisePropertyChanged("FaultMessageArray")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Field() As String
            Get
                Return Me.FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FieldField, value) <> true) Then
                    Me.FieldField = value
                    Me.RaisePropertyChanged("Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service() As String
            Get
                Return Me.ServiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceField, value) <> true) Then
                    Me.ServiceField = value
                    Me.RaisePropertyChanged("Service")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ServiceOperation() As String
            Get
                Return Me.ServiceOperationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceOperationField, value) <> true) Then
                    Me.ServiceOperationField = value
                    Me.RaisePropertyChanged("ServiceOperation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ServiceOperationParameter() As String
            Get
                Return Me.ServiceOperationParameterField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceOperationParameterField, value) <> true) Then
                    Me.ServiceOperationParameterField = value
                    Me.RaisePropertyChanged("ServiceOperationParameter")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XPath() As String
            Get
                Return Me.XPathField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XPathField, value) <> true) Then
                    Me.XPathField = value
                    Me.RaisePropertyChanged("XPath")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XmlLine() As String
            Get
                Return Me.XmlLineField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XmlLineField, value) <> true) Then
                    Me.XmlLineField = value
                    Me.RaisePropertyChanged("XmlLine")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XmlPosition() As String
            Get
                Return Me.XmlPositionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XmlPositionField, value) <> true) Then
                    Me.XmlPositionField = value
                    Me.RaisePropertyChanged("XmlPosition")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InfologMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InfologMessage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InfologMessageTypeField As axBOMService.InfologMessageType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InfologMessageType() As axBOMService.InfologMessageType
            Get
                Return Me.InfologMessageTypeField
            End Get
            Set
                If (Me.InfologMessageTypeField.Equals(value) <> true) Then
                    Me.InfologMessageTypeField = value
                    Me.RaisePropertyChanged("InfologMessageType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FaultMessage", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FaultMessage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodeField, value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InfologMessageType", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")>  _
    Public Enum InfologMessageType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Info = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Warning = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [Error] = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org", ConfigurationName:="axBOMService.V2AX_BOMListServices")>  _
    Public Interface V2AX_BOMListServices
        
        'CODEGEN: Generating message contract since the wrapper name (V2AX_BOMListServicesCreateBOMHeaderRequest) of message V2AX_BOMListServicesCreateBOMHeaderRequest does not match the default value (CreateBOMHeader)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/V2AX_BOMListServices/CreateBOMHeader", ReplyAction:="http://tempuri.org/V2AX_BOMListServices/CreateBOMHeaderResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(axBOMService.AifFault), Action:="http://tempuri.org/V2AX_BOMListServices/CreateBOMHeaderAifFaultFault", Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")>  _
        Function CreateBOMHeader(ByVal request As axBOMService.V2AX_BOMListServicesCreateBOMHeaderRequest) As axBOMService.V2AX_BOMListServicesCreateBOMHeaderResponse
        
        'CODEGEN: Generating message contract since the wrapper name (V2AX_BOMListServicesGetCompListRequest) of message V2AX_BOMListServicesGetCompListRequest does not match the default value (getCompList)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/V2AX_BOMListServices/getCompList", ReplyAction:="http://tempuri.org/V2AX_BOMListServices/getCompListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(axBOMService.AifFault), Action:="http://tempuri.org/V2AX_BOMListServices/getCompListAifFaultFault", Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")>  _
        Function getCompList(ByVal request As axBOMService.V2AX_BOMListServicesGetCompListRequest) As axBOMService.V2AX_BOMListServicesGetCompListResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_BOMListServicesCreateBOMHeaderRequest", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_BOMListServicesCreateBOMHeaderRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")>  _
        Public CallContext As axBOMService.CallContext
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public bOMContract As axBOMService.V2AX_BOMHeaderDataContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CallContext As axBOMService.CallContext, ByVal bOMContract As axBOMService.V2AX_BOMHeaderDataContract)
            MyBase.New
            Me.CallContext = CallContext
            Me.bOMContract = bOMContract
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_BOMListServicesCreateBOMHeaderResponse", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_BOMListServicesCreateBOMHeaderResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public response As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal response As Boolean)
            MyBase.New
            Me.response = response
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_BOMListServicesGetCompListRequest", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_BOMListServicesGetCompListRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")>  _
        Public CallContext As axBOMService.CallContext
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CallContext As axBOMService.CallContext)
            MyBase.New
            Me.CallContext = CallContext
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_BOMListServicesGetCompListResponse", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_BOMListServicesGetCompListResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public response() As axBOMService.V2AX_ItemListDataContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal response() As axBOMService.V2AX_ItemListDataContract)
            MyBase.New
            Me.response = response
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface V2AX_BOMListServicesChannel
        Inherits axBOMService.V2AX_BOMListServices, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class V2AX_BOMListServicesClient
        Inherits System.ServiceModel.ClientBase(Of axBOMService.V2AX_BOMListServices)
        Implements axBOMService.V2AX_BOMListServices
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function axBOMService_V2AX_BOMListServices_CreateBOMHeader(ByVal request As axBOMService.V2AX_BOMListServicesCreateBOMHeaderRequest) As axBOMService.V2AX_BOMListServicesCreateBOMHeaderResponse Implements axBOMService.V2AX_BOMListServices.CreateBOMHeader
            Return MyBase.Channel.CreateBOMHeader(request)
        End Function
        
        Public Function CreateBOMHeader(ByVal CallContext As axBOMService.CallContext, ByVal bOMContract As axBOMService.V2AX_BOMHeaderDataContract) As Boolean
            Dim inValue As axBOMService.V2AX_BOMListServicesCreateBOMHeaderRequest = New axBOMService.V2AX_BOMListServicesCreateBOMHeaderRequest()
            inValue.CallContext = CallContext
            inValue.bOMContract = bOMContract
            Dim retVal As axBOMService.V2AX_BOMListServicesCreateBOMHeaderResponse = CType(Me,axBOMService.V2AX_BOMListServices).CreateBOMHeader(inValue)
            Return retVal.response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function axBOMService_V2AX_BOMListServices_getCompList(ByVal request As axBOMService.V2AX_BOMListServicesGetCompListRequest) As axBOMService.V2AX_BOMListServicesGetCompListResponse Implements axBOMService.V2AX_BOMListServices.getCompList
            Return MyBase.Channel.getCompList(request)
        End Function
        
        Public Function getCompList(ByVal CallContext As axBOMService.CallContext) As axBOMService.V2AX_ItemListDataContract()
            Dim inValue As axBOMService.V2AX_BOMListServicesGetCompListRequest = New axBOMService.V2AX_BOMListServicesGetCompListRequest()
            inValue.CallContext = CallContext
            Dim retVal As axBOMService.V2AX_BOMListServicesGetCompListResponse = CType(Me,axBOMService.V2AX_BOMListServices).getCompList(inValue)
            Return retVal.response
        End Function
    End Class
End Namespace
