'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace axItemService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CallContext", [Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CallContext
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LanguageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LogonAsUserField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PartitionKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PropertyBagField As System.Collections.Generic.Dictionary(Of String, String)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Language() As String
            Get
                Return Me.LanguageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LanguageField, value) <> true) Then
                    Me.LanguageField = value
                    Me.RaisePropertyChanged("Language")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LogonAsUser() As String
            Get
                Return Me.LogonAsUserField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LogonAsUserField, value) <> true) Then
                    Me.LogonAsUserField = value
                    Me.RaisePropertyChanged("LogonAsUser")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MessageId() As String
            Get
                Return Me.MessageIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageIdField, value) <> true) Then
                    Me.MessageIdField = value
                    Me.RaisePropertyChanged("MessageId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PartitionKey() As String
            Get
                Return Me.PartitionKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PartitionKeyField, value) <> true) Then
                    Me.PartitionKeyField = value
                    Me.RaisePropertyChanged("PartitionKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PropertyBag() As System.Collections.Generic.Dictionary(Of String, String)
            Get
                Return Me.PropertyBagField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PropertyBagField, value) <> true) Then
                    Me.PropertyBagField = value
                    Me.RaisePropertyChanged("PropertyBag")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AifFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CustomDetailXmlField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaultMessageListArrayField() As axItemService.FaultMessageList
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InfologMessageListField() As axItemService.InfologMessage
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StackTraceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XppExceptionTypeField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CustomDetailXml() As String
            Get
                Return Me.CustomDetailXmlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CustomDetailXmlField, value) <> true) Then
                    Me.CustomDetailXmlField = value
                    Me.RaisePropertyChanged("CustomDetailXml")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaultMessageListArray() As axItemService.FaultMessageList()
            Get
                Return Me.FaultMessageListArrayField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaultMessageListArrayField, value) <> true) Then
                    Me.FaultMessageListArrayField = value
                    Me.RaisePropertyChanged("FaultMessageListArray")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InfologMessageList() As axItemService.InfologMessage()
            Get
                Return Me.InfologMessageListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InfologMessageListField, value) <> true) Then
                    Me.InfologMessageListField = value
                    Me.RaisePropertyChanged("InfologMessageList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StackTrace() As String
            Get
                Return Me.StackTraceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StackTraceField, value) <> true) Then
                    Me.StackTraceField = value
                    Me.RaisePropertyChanged("StackTrace")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XppExceptionType() As Integer
            Get
                Return Me.XppExceptionTypeField
            End Get
            Set
                If (Me.XppExceptionTypeField.Equals(value) <> true) Then
                    Me.XppExceptionTypeField = value
                    Me.RaisePropertyChanged("XppExceptionType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FaultMessageList", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FaultMessageList
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DocumentOperationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaultMessageArrayField() As axItemService.FaultMessage
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FieldField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceOperationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ServiceOperationParameterField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XPathField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XmlLineField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XmlPositionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Document() As String
            Get
                Return Me.DocumentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentField, value) <> true) Then
                    Me.DocumentField = value
                    Me.RaisePropertyChanged("Document")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DocumentOperation() As String
            Get
                Return Me.DocumentOperationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DocumentOperationField, value) <> true) Then
                    Me.DocumentOperationField = value
                    Me.RaisePropertyChanged("DocumentOperation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaultMessageArray() As axItemService.FaultMessage()
            Get
                Return Me.FaultMessageArrayField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaultMessageArrayField, value) <> true) Then
                    Me.FaultMessageArrayField = value
                    Me.RaisePropertyChanged("FaultMessageArray")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Field() As String
            Get
                Return Me.FieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FieldField, value) <> true) Then
                    Me.FieldField = value
                    Me.RaisePropertyChanged("Field")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Service() As String
            Get
                Return Me.ServiceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceField, value) <> true) Then
                    Me.ServiceField = value
                    Me.RaisePropertyChanged("Service")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ServiceOperation() As String
            Get
                Return Me.ServiceOperationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceOperationField, value) <> true) Then
                    Me.ServiceOperationField = value
                    Me.RaisePropertyChanged("ServiceOperation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ServiceOperationParameter() As String
            Get
                Return Me.ServiceOperationParameterField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ServiceOperationParameterField, value) <> true) Then
                    Me.ServiceOperationParameterField = value
                    Me.RaisePropertyChanged("ServiceOperationParameter")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XPath() As String
            Get
                Return Me.XPathField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XPathField, value) <> true) Then
                    Me.XPathField = value
                    Me.RaisePropertyChanged("XPath")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XmlLine() As String
            Get
                Return Me.XmlLineField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XmlLineField, value) <> true) Then
                    Me.XmlLineField = value
                    Me.RaisePropertyChanged("XmlLine")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XmlPosition() As String
            Get
                Return Me.XmlPositionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XmlPositionField, value) <> true) Then
                    Me.XmlPositionField = value
                    Me.RaisePropertyChanged("XmlPosition")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InfologMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InfologMessage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InfologMessageTypeField As axItemService.InfologMessageType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InfologMessageType() As axItemService.InfologMessageType
            Get
                Return Me.InfologMessageTypeField
            End Get
            Set
                If (Me.InfologMessageTypeField.Equals(value) <> true) Then
                    Me.InfologMessageTypeField = value
                    Me.RaisePropertyChanged("InfologMessageType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FaultMessage", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault"),  _
     System.SerializableAttribute()>  _
    Partial Public Class FaultMessage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodeField, value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InfologMessageType", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")>  _
    Public Enum InfologMessageType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Info = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Warning = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [Error] = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="V2AX_ItemListDataContract", [Namespace]:="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application"),  _
     System.SerializableAttribute()>  _
    Partial Public Class V2AX_ItemListDataContract
        Inherits axItemService.XppObjectBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChargesCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CompanyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IntegrationDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemGroupField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PcsControlledField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProductNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RemarksField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SearchNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SpecificationField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ChargesCode() As String
            Get
                Return Me.ChargesCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ChargesCodeField, value) <> true) Then
                    Me.ChargesCodeField = value
                    Me.RaisePropertyChanged("ChargesCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CompName() As String
            Get
                Return Me.CompNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompNameField, value) <> true) Then
                    Me.CompNameField = value
                    Me.RaisePropertyChanged("CompName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Company() As String
            Get
                Return Me.CompanyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CompanyField, value) <> true) Then
                    Me.CompanyField = value
                    Me.RaisePropertyChanged("Company")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescriptionField, value) <> true) Then
                    Me.DescriptionField = value
                    Me.RaisePropertyChanged("Description")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IntegrationDate() As Date
            Get
                Return Me.IntegrationDateField
            End Get
            Set
                If (Me.IntegrationDateField.Equals(value) <> true) Then
                    Me.IntegrationDateField = value
                    Me.RaisePropertyChanged("IntegrationDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ItemGroup() As String
            Get
                Return Me.ItemGroupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemGroupField, value) <> true) Then
                    Me.ItemGroupField = value
                    Me.RaisePropertyChanged("ItemGroup")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PcsControlled() As Boolean
            Get
                Return Me.PcsControlledField
            End Get
            Set
                If (Me.PcsControlledField.Equals(value) <> true) Then
                    Me.PcsControlledField = value
                    Me.RaisePropertyChanged("PcsControlled")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductName() As String
            Get
                Return Me.ProductNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNameField, value) <> true) Then
                    Me.ProductNameField = value
                    Me.RaisePropertyChanged("ProductName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ProductNo() As String
            Get
                Return Me.ProductNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProductNoField, value) <> true) Then
                    Me.ProductNoField = value
                    Me.RaisePropertyChanged("ProductNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Remarks() As String
            Get
                Return Me.RemarksField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RemarksField, value) <> true) Then
                    Me.RemarksField = value
                    Me.RaisePropertyChanged("Remarks")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SearchName() As String
            Get
                Return Me.SearchNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SearchNameField, value) <> true) Then
                    Me.SearchNameField = value
                    Me.RaisePropertyChanged("SearchName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Specification() As String
            Get
                Return Me.SpecificationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SpecificationField, value) <> true) Then
                    Me.SpecificationField = value
                    Me.RaisePropertyChanged("Specification")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="XppObjectBase", [Namespace]:="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(axItemService.V2AX_ItemListDataContract))>  _
    Partial Public Class XppObjectBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org", ConfigurationName:="axItemService.V2AX_ItemListServices")>  _
    Public Interface V2AX_ItemListServices
        
        'CODEGEN: Generating message contract since the wrapper name (V2AX_ItemListServicesUpdateItemExportStatusRequest) of message V2AX_ItemListServicesUpdateItemExportStatusRequest does not match the default value (updateItemExportStatus)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/V2AX_ItemListServices/updateItemExportStatus", ReplyAction:="http://tempuri.org/V2AX_ItemListServices/updateItemExportStatusResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(axItemService.AifFault), Action:="http://tempuri.org/V2AX_ItemListServices/updateItemExportStatusAifFaultFault", Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")>  _
        Function updateItemExportStatus(ByVal request As axItemService.V2AX_ItemListServicesUpdateItemExportStatusRequest) As axItemService.V2AX_ItemListServicesUpdateItemExportStatusResponse
        
        'CODEGEN: Generating message contract since the wrapper name (V2AX_ItemListServicesGetItemListRequest) of message V2AX_ItemListServicesGetItemListRequest does not match the default value (getItemList)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/V2AX_ItemListServices/getItemList", ReplyAction:="http://tempuri.org/V2AX_ItemListServices/getItemListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(axItemService.AifFault), Action:="http://tempuri.org/V2AX_ItemListServices/getItemListAifFaultFault", Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")>  _
        Function getItemList(ByVal request As axItemService.V2AX_ItemListServicesGetItemListRequest) As axItemService.V2AX_ItemListServicesGetItemListResponse
        
        'CODEGEN: Generating message contract since the wrapper name (V2AX_ItemListServicesCreateItemRequest) of message V2AX_ItemListServicesCreateItemRequest does not match the default value (CreateItem)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/V2AX_ItemListServices/CreateItem", ReplyAction:="http://tempuri.org/V2AX_ItemListServices/CreateItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(axItemService.AifFault), Action:="http://tempuri.org/V2AX_ItemListServices/CreateItemAifFaultFault", Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")>  _
        Function CreateItem(ByVal request As axItemService.V2AX_ItemListServicesCreateItemRequest) As axItemService.V2AX_ItemListServicesCreateItemResponse
        
        'CODEGEN: Generating message contract since the wrapper name (V2AX_ItemListServicesGetCompListRequest) of message V2AX_ItemListServicesGetCompListRequest does not match the default value (getCompList)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/V2AX_ItemListServices/getCompList", ReplyAction:="http://tempuri.org/V2AX_ItemListServices/getCompListResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(axItemService.AifFault), Action:="http://tempuri.org/V2AX_ItemListServices/getCompListAifFaultFault", Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")>  _
        Function getCompList(ByVal request As axItemService.V2AX_ItemListServicesGetCompListRequest) As axItemService.V2AX_ItemListServicesGetCompListResponse
        
        'CODEGEN: Generating message contract since the wrapper name (V2AX_ItemListServicesItemExistsRequest) of message V2AX_ItemListServicesItemExistsRequest does not match the default value (itemExists)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/V2AX_ItemListServices/itemExists", ReplyAction:="http://tempuri.org/V2AX_ItemListServices/itemExistsResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(axItemService.AifFault), Action:="http://tempuri.org/V2AX_ItemListServices/itemExistsAifFaultFault", Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")>  _
        Function itemExists(ByVal request As axItemService.V2AX_ItemListServicesItemExistsRequest) As axItemService.V2AX_ItemListServicesItemExistsResponse
        
        'CODEGEN: Generating message contract since the wrapper name (V2AX_ItemListServicesModifyItemRequest) of message V2AX_ItemListServicesModifyItemRequest does not match the default value (modifyItem)
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/V2AX_ItemListServices/modifyItem", ReplyAction:="http://tempuri.org/V2AX_ItemListServices/modifyItemResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(axItemService.AifFault), Action:="http://tempuri.org/V2AX_ItemListServices/modifyItemAifFaultFault", Name:="AifFault", [Namespace]:="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")>  _
        Function modifyItem(ByVal request As axItemService.V2AX_ItemListServicesModifyItemRequest) As axItemService.V2AX_ItemListServicesModifyItemResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesUpdateItemExportStatusRequest", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesUpdateItemExportStatusRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")>  _
        Public CallContext As axItemService.CallContext
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public itemId As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=1)>  _
        Public integrationDate As Date
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=2)>  _
        Public status As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CallContext As axItemService.CallContext, ByVal itemId As String, ByVal integrationDate As Date, ByVal status As Integer)
            MyBase.New
            Me.CallContext = CallContext
            Me.itemId = itemId
            Me.integrationDate = integrationDate
            Me.status = status
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesUpdateItemExportStatusResponse", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesUpdateItemExportStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public response As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal response As Boolean)
            MyBase.New
            Me.response = response
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesGetItemListRequest", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesGetItemListRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")>  _
        Public CallContext As axItemService.CallContext
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CallContext As axItemService.CallContext)
            MyBase.New
            Me.CallContext = CallContext
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesGetItemListResponse", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesGetItemListResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public response() As axItemService.V2AX_ItemListDataContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal response() As axItemService.V2AX_ItemListDataContract)
            MyBase.New
            Me.response = response
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesCreateItemRequest", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesCreateItemRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")>  _
        Public CallContext As axItemService.CallContext
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public v2AX_ItemListContract As axItemService.V2AX_ItemListDataContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CallContext As axItemService.CallContext, ByVal v2AX_ItemListContract As axItemService.V2AX_ItemListDataContract)
            MyBase.New
            Me.CallContext = CallContext
            Me.v2AX_ItemListContract = v2AX_ItemListContract
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesCreateItemResponse", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesCreateItemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public response As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal response As Boolean)
            MyBase.New
            Me.response = response
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesGetCompListRequest", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesGetCompListRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")>  _
        Public CallContext As axItemService.CallContext
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CallContext As axItemService.CallContext)
            MyBase.New
            Me.CallContext = CallContext
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesGetCompListResponse", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesGetCompListResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public response() As axItemService.V2AX_ItemListDataContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal response() As axItemService.V2AX_ItemListDataContract)
            MyBase.New
            Me.response = response
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesItemExistsRequest", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesItemExistsRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")>  _
        Public CallContext As axItemService.CallContext
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public itemId As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CallContext As axItemService.CallContext, ByVal itemId As String)
            MyBase.New
            Me.CallContext = CallContext
            Me.itemId = itemId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesItemExistsResponse", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesItemExistsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public response As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal response As Boolean)
            MyBase.New
            Me.response = response
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesModifyItemRequest", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesModifyItemRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")>  _
        Public CallContext As axItemService.CallContext
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public v2AX_ItemListContract As axItemService.V2AX_ItemListDataContract
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CallContext As axItemService.CallContext, ByVal v2AX_ItemListContract As axItemService.V2AX_ItemListDataContract)
            MyBase.New
            Me.CallContext = CallContext
            Me.v2AX_ItemListContract = v2AX_ItemListContract
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="V2AX_ItemListServicesModifyItemResponse", WrapperNamespace:="http://tempuri.org", IsWrapped:=true)>  _
    Partial Public Class V2AX_ItemListServicesModifyItemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org", Order:=0)>  _
        Public response As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal response As Boolean)
            MyBase.New
            Me.response = response
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface V2AX_ItemListServicesChannel
        Inherits axItemService.V2AX_ItemListServices, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class V2AX_ItemListServicesClient
        Inherits System.ServiceModel.ClientBase(Of axItemService.V2AX_ItemListServices)
        Implements axItemService.V2AX_ItemListServices
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function axItemService_V2AX_ItemListServices_updateItemExportStatus(ByVal request As axItemService.V2AX_ItemListServicesUpdateItemExportStatusRequest) As axItemService.V2AX_ItemListServicesUpdateItemExportStatusResponse Implements axItemService.V2AX_ItemListServices.updateItemExportStatus
            Return MyBase.Channel.updateItemExportStatus(request)
        End Function
        
        Public Function updateItemExportStatus(ByVal CallContext As axItemService.CallContext, ByVal itemId As String, ByVal integrationDate As Date, ByVal status As Integer) As Boolean
            Dim inValue As axItemService.V2AX_ItemListServicesUpdateItemExportStatusRequest = New axItemService.V2AX_ItemListServicesUpdateItemExportStatusRequest()
            inValue.CallContext = CallContext
            inValue.itemId = itemId
            inValue.integrationDate = integrationDate
            inValue.status = status
            Dim retVal As axItemService.V2AX_ItemListServicesUpdateItemExportStatusResponse = CType(Me,axItemService.V2AX_ItemListServices).updateItemExportStatus(inValue)
            Return retVal.response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function axItemService_V2AX_ItemListServices_getItemList(ByVal request As axItemService.V2AX_ItemListServicesGetItemListRequest) As axItemService.V2AX_ItemListServicesGetItemListResponse Implements axItemService.V2AX_ItemListServices.getItemList
            Return MyBase.Channel.getItemList(request)
        End Function
        
        Public Function getItemList(ByVal CallContext As axItemService.CallContext) As axItemService.V2AX_ItemListDataContract()
            Dim inValue As axItemService.V2AX_ItemListServicesGetItemListRequest = New axItemService.V2AX_ItemListServicesGetItemListRequest()
            inValue.CallContext = CallContext
            Dim retVal As axItemService.V2AX_ItemListServicesGetItemListResponse = CType(Me,axItemService.V2AX_ItemListServices).getItemList(inValue)
            Return retVal.response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function axItemService_V2AX_ItemListServices_CreateItem(ByVal request As axItemService.V2AX_ItemListServicesCreateItemRequest) As axItemService.V2AX_ItemListServicesCreateItemResponse Implements axItemService.V2AX_ItemListServices.CreateItem
            Return MyBase.Channel.CreateItem(request)
        End Function
        
        Public Function CreateItem(ByVal CallContext As axItemService.CallContext, ByVal v2AX_ItemListContract As axItemService.V2AX_ItemListDataContract) As Boolean
            Dim inValue As axItemService.V2AX_ItemListServicesCreateItemRequest = New axItemService.V2AX_ItemListServicesCreateItemRequest()
            inValue.CallContext = CallContext
            inValue.v2AX_ItemListContract = v2AX_ItemListContract
            Dim retVal As axItemService.V2AX_ItemListServicesCreateItemResponse = CType(Me,axItemService.V2AX_ItemListServices).CreateItem(inValue)
            Return retVal.response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function axItemService_V2AX_ItemListServices_getCompList(ByVal request As axItemService.V2AX_ItemListServicesGetCompListRequest) As axItemService.V2AX_ItemListServicesGetCompListResponse Implements axItemService.V2AX_ItemListServices.getCompList
            Return MyBase.Channel.getCompList(request)
        End Function
        
        Public Function getCompList(ByVal CallContext As axItemService.CallContext) As axItemService.V2AX_ItemListDataContract()
            Dim inValue As axItemService.V2AX_ItemListServicesGetCompListRequest = New axItemService.V2AX_ItemListServicesGetCompListRequest()
            inValue.CallContext = CallContext
            Dim retVal As axItemService.V2AX_ItemListServicesGetCompListResponse = CType(Me,axItemService.V2AX_ItemListServices).getCompList(inValue)
            Return retVal.response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function axItemService_V2AX_ItemListServices_itemExists(ByVal request As axItemService.V2AX_ItemListServicesItemExistsRequest) As axItemService.V2AX_ItemListServicesItemExistsResponse Implements axItemService.V2AX_ItemListServices.itemExists
            Return MyBase.Channel.itemExists(request)
        End Function
        
        Public Function itemExists(ByVal CallContext As axItemService.CallContext, ByVal itemId As String) As Boolean
            Dim inValue As axItemService.V2AX_ItemListServicesItemExistsRequest = New axItemService.V2AX_ItemListServicesItemExistsRequest()
            inValue.CallContext = CallContext
            inValue.itemId = itemId
            Dim retVal As axItemService.V2AX_ItemListServicesItemExistsResponse = CType(Me,axItemService.V2AX_ItemListServices).itemExists(inValue)
            Return retVal.response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function axItemService_V2AX_ItemListServices_modifyItem(ByVal request As axItemService.V2AX_ItemListServicesModifyItemRequest) As axItemService.V2AX_ItemListServicesModifyItemResponse Implements axItemService.V2AX_ItemListServices.modifyItem
            Return MyBase.Channel.modifyItem(request)
        End Function
        
        Public Function modifyItem(ByVal CallContext As axItemService.CallContext, ByVal v2AX_ItemListContract As axItemService.V2AX_ItemListDataContract) As Boolean
            Dim inValue As axItemService.V2AX_ItemListServicesModifyItemRequest = New axItemService.V2AX_ItemListServicesModifyItemRequest()
            inValue.CallContext = CallContext
            inValue.v2AX_ItemListContract = v2AX_ItemListContract
            Dim retVal As axItemService.V2AX_ItemListServicesModifyItemResponse = CType(Me,axItemService.V2AX_ItemListServices).modifyItem(inValue)
            Return retVal.response
        End Function
    End Class
End Namespace
